name: Restore FS button

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/patch-fs-btn.yml"

permissions:
  contents: write

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Edit main.js
        run: python3 scripts/restore_fs_btn.py
